fix: Microsoft.OpenAPI package reference conflict
domaindrivendev/Swashbuckle.AspNetCore pull request #1718
Opened 2020-06-23 15:27 UTC by korifeich

Add upper bound to Miicrosoft.OpenAPI package reference to Swashbuckle.AspNetCore.Swagger project to be less than 1.2.0 as it breaks contains breaking changes for  Swashbuckle.AspNetCore.Swagger project

fixes #1717

2020-06-24 18:06 UTC, CumpsD commented
Better to put some pressure on them to fix it properly so everybody can move to 1.2.x (or 1.3.0 if they want to name it that)

https://github.com/microsoft/OpenAPI.NET/issues/487#issuecomment-648976686

2020-06-24 21:58 UTC, CumpsD commented
Wait to merge this, fixing it at the source: https://github.com/microsoft/OpenAPI.NET/pull/492

2020-06-25 01:54 UTC, CumpsD commented on src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj
> +    <PackageReference Include="Microsoft.OpenApi" Version="[1.1.4,1.2.0)" />
```suggestion
    <PackageReference Include="Microsoft.OpenApi" Version="1.2.2" />
```

We fixed it at the source, Microsoft released a version without the breaking changes. Swashbuckle can now target 1.2.2

2020-09-10 06:34 UTC, RFlipper requested changes
The PR is outdated and should be rejected

2020-09-10 08:13 UTC, closed without merging